#!/bin/bash

#PBS -S /bin/bash
#PBS -l pmem=1000m
#PBS -l feature=X5675
#PBS -l nodes=1:ppn=12
#PBS -l walltime=4:00:00
#PBS -m bea
#PBS -M koch.eric.w@gmail.com
#PBS -l epilogue=/home/ekoch/code_repos/simscript/epilogue.sh

source /home/ekoch/.bashrc

echo "Starting at: `date`"
for face in {0..2}
    do
    mpirun -np 11 python2.7 /lustre/home/ekoch/code_repos/TurbuStat/Examples/jasper/complete_comparisons.py /lustre/home/ekoch/sims/complete/ /lustre/home/ekoch/sims/SimSuite8_noise/ $face Des_to_Obs MPI /lustre/home/ekoch/sims/results/des_to_obs/ SimSuite8_complete
done
echo "Exited with code $? at: `date`"