#!/bin/bash

#PBS -S /bin/bash
#PBS -l pmem=3500mb
#PBS -l feature=X5675
#PBS -l nodes=1:ppn=12
#PBS -l naccesspolicy=singlejob
#PBS -l walltime=20:00:00
#PBS -m bea
#PBS -M koch.eric.w@gmail.com
#PBS -l epilogue=/home/ekoch/code_repos/simscript/epilogue.sh

source /home/ekoch/.bashrc

echo "Starting at: `date`"
for face1 in {0..2}
    do
    for face2 in {0..2}
    do
        # mpirun -np 11 python2.7 /lustre/home/ekoch/code_repos/TurbuStat/Examples/jasper/output_mpi.py /lustre/home/ekoch/sims/SimSuite8/ fid_comp $face1 $face2 max SimSuite8_comparisons T T /lustre/home/ekoch/sims/results/noise_same_results/
        mpirun -np 11 python2.7 /lustre/home/ekoch/code_repos/TurbuStat/Examples/jasper/output_mpi_load.py /lustre/home/ekoch/sims/SimSuite8/ fid_comp $face1 $face2 max SimSuite8_comparisons T T /lustre/home/ekoch/sims/results/noise_same_results/
    done
done
echo "Exited with code $? at: `date`"
