version: 2

build:
  image: latest

# Install regular dependencies.
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

dependencies:
    - python=>3
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - statsmodels
    - scikit-learn
    - scikit-image
    - mock
    - sphinx_bootstrap_theme
    - pip:
      - git+https://github.com/dendrograms/astrodendro.git
      - git+https://github.com/radio-astro-tools/spectral-cube.git
      - git+https://github.com/radio-astro-tools/radio-beam.git
