language: python

python:
    - 2.6
    - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    # Create a new environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip cython nose
    - source activate test

    # Now install dependencies
    - conda --yes install numpy
    - conda --yes install scipy
    - conda --yes install matplotlib
    - conda --yes install scikits-image
    - conda --yes install pandas
    - conda --yes install statsmodels
    - conda --yes install scikit-learn
    - conda install git+https://github.com/astropy/astropy.git@v0.4rc1

    # Use pip to install development versions
    - sudo pip install git+https://github.com/dendrograms/astrodendro.git
    ## Eventually add on spectral-cube and signal-id

script:
    nosetests turbustat/tests/