language: python

python:
    - 2.6
    - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    # Create a new environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip cython nose
    - source activate test

    # Now install dependencies
    - conda install --yes numpy
    - conda install --yes scipy
    - conda install --yes matplotlib
    - conda install --yes scikits-image
    - conda install --yes pandas
    - conda install --yes statsmodels
    - conda install --yes scikit-learn
    - conda install --yes astropy==0.4rc1

    # Use pip to install development versions
    - pip install git+https://github.com/dendrograms/astrodendro.git
    ## Eventually add on spectral-cube and signal-id

script:
    - python setup.py install
    - nosetests turbustat/tests/