language: python

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - dvipng
            - libfftw3-dev

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - SETUP_XVFB=True
        - ON_TRAVIS=True
        - TOXENV=''
        - TOXARGS=''
        - TOXPOSARGS=''
        - MPLBACKEND='Agg'

matrix:
    include:

        - python: 3.7
          env: TOXENV='py37-test'
          name: "Python 3.7 with minimal dependencies"

        - python: 3.6
          env: TOXENV='py36-test'
          name: "Python 3.6 with minimal dependencies"

        - python: 3.6
          env: TOXENV='py36-test-dev'
          name: "Python 3.6, and dev versions of key dependencies"

        - python: 3.8
          env: TOXENV='py38-test-all-dev'
          name: "Python 3.8, all dependencies, and dev versions of key dependencies"

        - language: c
          os: osx
          env: PYTHON_VERSION=3.7 TOXENV='py37-test-all'
          name: "Python 3.7 with all dependencies on MacOS X"

        - language: c
          os: windows
          env: PYTHON_VERSION=3.7 TOXENV='py37-test-all-dev'
          name: "Python 3.7, all dependencies, and dev versions of key dependencies on Windows"

        - python: 3.8
          env: TOXENV='build_docs'
          name: "Documentation"

before_install:
    # We need a full clone to make sure setuptools_scm
    # works properly
    - git fetch --unshallow .
    - git fetch --depth=1000000

    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        export DISPLAY=:99.0;
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset;
      fi

install:
    # language: python is only available for Linux, so for other platforms
    # we need to use ci-helpers to set up Python.
    - if [[ $TRAVIS_OS_NAME == osx || $TRAVIS_OS_NAME == windows ]]; then
        git clone git://github.com/astropy/ci-helpers.git;
        source ci-helpers/travis/setup_conda.sh;
      fi


script:
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS

after_success:
    - pip install coveralls coverage
    - coverage combine .tmp/*/.coverage
    - coverage report
    - coveralls



# env:
#     global:
#         - PYTHON_VERSION=3.7
#         - NUMPY_VERSION=1.17
#         - ASTROPY_VERSION=stable
#         - MAIN_CMD='python setup.py'
#         - SETUP_CMD='test'
#         - PIP_DEPENDENCIES='git+https://github.com/dendrograms/astrodendro.git git+https://github.com/radio-astro-tools/radio-beam.git git+https://github.com/radio-astro-tools/spectral-cube.git'
#         - EVENT_TYPE='pull_request push'

#         - CONDA_CHANNELS='astropy-ci-extras astropy'
#         - SETUP_XVFB=True

#         - CONDA_DEPENDENCIES='scipy matplotlib pandas statsmodels scikit-learn scikit-image cython'

#         - MPLBACKEND="Agg"

#     matrix:
#         - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
#         - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
#         - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
#         - PYTHON_VERSION=3.6 SETUP_CMD='egg_info'

# matrix:

#     # Don't wait for allowed failures
#     fast_finish: true

#     include:
#         # Try MacOS X
#         # - os: osx
#           # env: SETUP_CMD='test'

#         # Do a coverage test.
#         - os: linux
#           env: SETUP_CMD='test --coverage'
#                PIP_DEPENDENCIES='emcee pyfftw git+https://github.com/dendrograms/astrodendro.git git+https://github.com/radio-astro-tools/spectral-cube.git git+https://github.com/radio-astro-tools/radio-beam.git'
#         # Check for sphinx doc build warnings - we do this first because it
#         # may run for a long time
#         - os: linux
#           env: SETUP_CMD='build_docs -w'
#                CONDA_DEPENDENCIES='sip<4.19 pytest<3.9.3 scipy matplotlib pandas statsmodels scikit-learn mock sphinx_bootstrap_theme cython sphinx_astropy'


# install:
#     - git clone git://github.com/astropy/ci-helpers.git
#     - source ci-helpers/travis/setup_conda.sh

# script:
#    - $MAIN_CMD $SETUP_CMD

# after_success:
#     - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='turbustat/tests/coveragerc'; fi