language: python

sudo : false

python:
    - 2.6
    - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    # Create a new environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip cython nose
    - source activate test

    # Now install dependencies
    - conda install --yes numpy==1.9.0
    - conda install --yes scipy
    - conda install --yes matplotlib
    - conda install --yes pandas
    - conda install --yes statsmodels
    - conda install --yes scikit-learn
    - conda install --yes astropy

    # Use pip to install development versions
    - pip install git+https://github.com/dendrograms/astrodendro.git
    - pip install git+https://github.com/radio-astro-tools/spectral-cube.git
    - pip install git+https://github.com/radio-astro-tools/signal-id.git
    - pip install git+https://github.com/radio-astro-tools/radio_beam.git

script:
    - python setup.py install
    - nosetests turbustat/tests/