#!/bin/bash

#PBS -S /bin/bash
#PBS -l pmem=4000m
#PBS -l feature=X5675
#PBS -l nodes=1:ppn=12
#PBS -l walltime=3:00:00
#PBS -m bea
#PBS -M koch.eric.w@gmail.com
#PBS -l epilogue=/home/ekoch/code_repos/simscript/epilogue.sh

source /home/ekoch/.bashrc

echo "Starting at: `date`"
mpirun -np 12 python2.7 /lustre/home/ekoch/code_repos/TurbuStat/Examples/pairwise/tstep_compare/timestep_pairwise.py /lustre/home/ekoch/sims/SimSuite8/ 24 22 0 /lustre/home/ekoch/sims/tstep_pairwise/
echo "Exited with code $? at: `date`"
